---
title: "Initial Korean Covid 19"
author: "Tyler Hamblin"
date: "10 October 2023"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
require(tidyverse)
require(tigerstats)
require(lubridate)
kRdata <- read.csv(file = 'kRdata.csv')
kRdata <- kRdata %>%
mutate(across(where(is.character), as.factor))

```
### Data is from the Patient_Info dataset from South Korea 1 Jan to 1 May 2020
### This data was retrieved from a downloadable zip file from kaggle

Some of the data was uncoded for sex - sex must be just male or female
77 of the data entries were coded sex  as blank, so we omit these.
state of a patient must be died or alive - we adjust that as well   
  
# Your Question - Is dying independent of sex?



## Methods

According to the data found under kRdata we are trying to find out if there is a difference in the category Sex (male/female) in regards to COVID-19. Essentially we could prove if the virus is more harmful towards men or women based on the percentage of people from each group that pass away after contracting it. We can reach this conclusion by using Cat~Cat helper files from the CandP zip to help us decipher these statistics. 



## Graphical results - use ggplot commands to do this  



  





  
## Numerical results


## Inferential results 




## Conclusions

